Risk score reasons
maxmind/minfraud-api-java pull request #398
Opened 2024-08-27 17:49 UTC by marselester

2024-08-27 20:35 UTC, oschwald submitted a review, later dismissed

2024-08-27 20:35 UTC, oschwald commented on src/main/java/com/maxmind/minfraud/response/FactorsResponse.java
> +        List<RiskScoreReason> riskScoreReasons,
This is a deprecated constructor that only exists for compatibility. You shouldn't be adding new parameters.

We will also need to add another deprecated constructor that matches the main constructor before `RiskScoreReasons`  was added.

2024-08-30 22:39 UTC, ugexe requested changes

2024-08-30 22:39 UTC, ugexe commented on src/main/java/com/maxmind/minfraud/response/FactorsResponse.java
> +     * @param riskScoreReasons A list containing objects that describe risk score reasons
Maybe this description should be moved to the model class and referenced here ala `A list containing {@code RiskScoreReason} model objects.` That seems to be more consistent with how the other params are documented.

2024-08-30 22:39 UTC, ugexe commented on src/main/java/com/maxmind/minfraud/response/RiskScoreReason.java
> +     *     This will be an empty list if there are no reasons.
The spacing / line breaks of some of these comments is off

2024-08-30 22:39 UTC, ugexe commented on src/test/java/com/maxmind/minfraud/response/FactorsResponseTest.java
> +            factors.getRiskScoreReasons().get(0).getReasons().get(0).getCode(),
Should we continue adding length checks to the new tests for all the libraries?

2024-08-30 22:39 UTC, ugexe commented on src/main/java/com/maxmind/minfraud/response/FactorsResponse.java
> +            List<RiskScoreReason> riskScoreReasons,
This shouldn't be included in a deprecated constructor

2024-09-03 16:36 UTC, marselester commented on src/main/java/com/maxmind/minfraud/response/FactorsResponse.java
> +     * @param riskScoreReasons A list containing objects that describe risk score reasons
I've tried that but the meaning gets lost because the description is about a list of objects and when it can be empty.

2024-09-03 20:27 UTC, ugexe approved these changes

2024-09-03 20:28 UTC, merged